Implement update/delete/insert functions logic for the universal dashboard endpoint
ElGarash/meetings pull request #15
Opened 2021-08-01 10:32 UTC by nooreldeensalah

### Summary of changes:
- Changed the database schema into many-to-many relationships.
- Refactored GitHub functions logic into a separate ~~file~~ package.
- Implemented update/delete/insert functions.
- Updated function routes to follow RESTful API principles.
- Added error handling for all the functions.

2021-08-01 10:35 UTC, nooreldeensalah commented
Here is how the main branch files structure looks like 
![image](https://user-images.githubusercontent.com/61914159/127767755-c2ee794c-b4c8-43e3-9cb3-0856fe9572d1.png)

Should I rename any file/directory? (Note that it won't affect the function URL at Azure since I explicitly set it in the JSON files).

2021-08-01 10:57 UTC, AbdulrhmnGhanem requested changes

2021-08-01 10:57 UTC, AbdulrhmnGhanem commented on functions/dashboard/function.json
> +      "route": "dashboard/{resources:alpha?}/{id:int?}"
What does this question mark mean?

2021-08-01 10:57 UTC, AbdulrhmnGhanem commented on functions/dashboard/main.py
> +        return func.HttpResponse("Method not allowed", status_code=405)
This function is huge. Just use it for dispatching for other functions.

2021-08-01 10:57 UTC, AbdulrhmnGhanem commented on functions/dashboard/main.py
> +        return {"message": "A meeting with the same date and time already exists", "status_code": 409}
This assumes errors will only occur because `"A meeting with the same date and time already exists"`. The exception message should be inspected not assumed.

2021-08-01 10:57 UTC, AbdulrhmnGhanem commented on functions/dashboard/main.py
> +    db_labels = set(map(get_name, session.query(Label).all()))
What is the purpose of the set?

2021-08-01 10:57 UTC, AbdulrhmnGhanem commented on functions/dashboard/main.py
> +    get_name = lambda model: model.name
https://docs.python.org/3/library/operator.html#operator.attrgetter.
Also, prefer list comprehensions over `map`.

2021-08-01 10:57 UTC, AbdulrhmnGhanem commented on functions/dashboard/main.py
> +
New line, just use black :smile:

2021-08-01 10:57 UTC, AbdulrhmnGhanem commented on functions/github/__init__.py
> +REPO_FULL_NAME = "ElGarash/Jitsi-Meetings-Dashboard"
Old repo name.

2021-08-01 10:57 UTC, AbdulrhmnGhanem commented on functions/github/__init__.py
> +    )
New line, just use black :smile:

2021-08-01 10:59 UTC, nooreldeensalah commented on functions/dashboard/function.json
> +      "route": "dashboard/{resources:alpha?}/{id:int?}"
Means that the route parameter is optional.

2021-08-01 11:01 UTC, AbdulrhmnGhanem commented on functions/dashboard/function.json
> +      "route": "dashboard/{resources:alpha?}/{id:int?}"
Why is it optional?

2021-08-01 11:01 UTC, nooreldeensalah commented on functions/dashboard/main.py
> +        return func.HttpResponse("Method not allowed", status_code=405)
From what I initially understood, that we will be using a single function, that will be used to dispatch the C~~R~~UD operations, the C~~R~~UD logic with SQLAlchemy is already encapsulated as functions in the same file.

2021-08-01 11:02 UTC, nooreldeensalah commented on functions/dashboard/main.py
> +    db_labels = set(map(get_name, session.query(Label).all()))
Membership test for a set is `O(1)` unlike a list.

2021-08-01 11:03 UTC, nooreldeensalah commented on functions/dashboard/main.py
> +
😅

2021-08-01 11:03 UTC, nooreldeensalah commented on functions/github/__init__.py
> +REPO_FULL_NAME = "ElGarash/Jitsi-Meetings-Dashboard"
Oh yeah, I forgot to update it, but somehow GitHub brings no errors with it, it's probably clever with redirections.

Will update it.

2021-08-01 11:05 UTC, nooreldeensalah commented on functions/dashboard/function.json
> +      "route": "dashboard/{resources:alpha?}/{id:int?}"
The `POST` request that is used to insert a meeting and it's participants and labels in the `insert` function, requires no route parameters, only a request body.

2021-08-01 11:08 UTC, AbdulrhmnGhanem commented on functions/dashboard/main.py
> +    db_labels = set(map(get_name, session.query(Label).all()))
Just good old premature optimization :laughing:
To construct a set from a list it takes `O(n)` then the lookup will take `O(1)`. Sets are useful for multiple lookups; when a set is constructed once and used over and over again. for single lookup, lists are faster.

2021-08-01 11:10 UTC, AbdulrhmnGhanem commented on functions/dashboard/function.json
> +      "route": "dashboard/{resources:alpha?}/{id:int?}"
I think it should have resource = meeting

2021-08-01 11:11 UTC, AbdulrhmnGhanem commented on functions/dashboard/main.py
> +        return func.HttpResponse("Method not allowed", status_code=405)
Also, dispatch on the request type.

2021-08-01 11:13 UTC, nooreldeensalah commented on functions/dashboard/main.py
> +        return func.HttpResponse("Method not allowed", status_code=405)
What is the request type?
And how does it different from the request method?

2021-08-01 11:15 UTC, AbdulrhmnGhanem commented on functions/dashboard/main.py
> +        return func.HttpResponse("Method not allowed", status_code=405)
I meant the request method.

2021-08-02 03:38 UTC, AbdulrhmnGhanem requested changes

2021-08-02 03:38 UTC, AbdulrhmnGhanem commented on functions/dashboard/main.py
> +        db_labels = [get_name(label) for label in session.query(Label).all()]
can't we load only the `name` in the first place?

2021-08-02 03:38 UTC, AbdulrhmnGhanem commented on functions/dashboard/main.py
> +    return func.HttpResponse("Resource successfully inserted", status_code=201)
This function is huge break it into smaller functions.

2021-08-02 03:38 UTC, AbdulrhmnGhanem commented on functions/dashboard/main.py
> +    return func.HttpResponse("Successfully updated the resource", status_code=200)
This function is huge break it into smaller functions.

2021-08-02 03:40 UTC, nooreldeensalah commented on functions/dashboard/main.py
> +        db_labels = [get_name(label) for label in session.query(Label).all()]
`session.query(Participant).all()` returns `Participant` instances, each of which has a name and an id, according to the `Participant` model definition in `models.py`

2021-08-02 04:06 UTC, AbdulrhmnGhanem commented on functions/dashboard/main.py
> +        db_labels = [get_name(label) for label in session.query(Label).all()]
Have you tried any of these?
https://docs.sqlalchemy.org/en/14/orm/loading_columns.html#sqlalchemy.orm.load_only
https://stackoverflow.com/a/37134248/12113647

2021-08-02 04:09 UTC, AbdulrhmnGhanem commented on functions/dashboard/main.py
> +
Set up a pre-commit hook with black to avoid these mistakes.

2021-08-02 04:42 UTC, nooreldeensalah commented on functions/dashboard/main.py
> +        db_labels = [get_name(label) for label in session.query(Label).all()]
Neither of them worked, I would still have to use list comprehensions to get the name.

2021-08-02 04:46 UTC, AbdulrhmnGhanem approved these changes

2021-08-02 04:47 UTC, merged